#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR="${GITHUB_WORKSPACE:-$(pwd)}"
LOG_FILE="${TARGET_DIR}/fairydust_build.log"
REPO_URL="https://github.com/AsahiLinux/linux.git"
BRANCH="fairydust"

SAFE_JOBS=$(nproc)
if [ "$SAFE_JOBS" -gt 4 ]; then SAFE_JOBS=4; fi
export MAKEFLAGS="-j${SAFE_JOBS}"

exec > >(tee -a "${LOG_FILE}") 2>&1

echo "=== Build environment ==="
uname -a
free -h || true
ulimit -a || true

echo "=== [1/6] Starting Cloud Fairydust Kernel Build: $(date) ==="

cd "$TARGET_DIR"
rm -rf linux dist

echo "=== [2/6] Shallow cloning ${BRANCH} branch ==="
git clone --branch "$BRANCH" --depth 1 "$REPO_URL" linux
cd linux

echo "=== [3/6] Preparing Asahi + Fairydust kernel configuration ==="

# Start from the normal ARM64 baseline, then merge the Asahi configuration
# shipped by the exact Fairydust kernel branch being built.
make defconfig
./scripts/kconfig/merge_config.sh -m .config arch/arm64/configs/asahi.config

if ! make rustavailable; then
    echo "ERROR: Rust toolchain is not properly configured for kernel build!"
    exit 1
fi

# Fairydust DisplayPort/Type-C configuration. Keep these on top of the
# upstream Asahi configuration so DP/DSC support is not lost when the base
# configuration changes.
scripts/config --enable CONFIG_RUST
scripts/config --enable CONFIG_DRM_APPLE
scripts/config --enable CONFIG_TYPEC_APPLE
scripts/config --enable CONFIG_TYPEC_DP_ALTMODE
scripts/config --enable CONFIG_TYPEC_NVIDIA_ALTMODE
scripts/config --enable CONFIG_TYPEC_TBT_ALTMODE
scripts/config --enable CONFIG_APPLE_MAILBOX

make olddefconfig

echo "=== Selected Asahi/Fairydust configuration ==="
for CONFIG in \
  CONFIG_ARCH_APPLE \
  CONFIG_DRM_ASAHI \
  CONFIG_DRM_APPLE \
  CONFIG_DRM_ADP \
  CONFIG_PHY_APPLE_DPTX \
  CONFIG_MUX_APPLE_DPXBAR \
  CONFIG_TYPEC_APPLE \
  CONFIG_TYPEC_DP_ALTMODE \
  CONFIG_TYPEC_NVIDIA_ALTMODE \
  CONFIG_TYPEC_TBT_ALTMODE \
  CONFIG_USB_DWC3_APPLE \
  CONFIG_USB_XHCI_PCI_ASMEDIA \
  CONFIG_PCIE_APPLE \
  CONFIG_NVME_APPLE \
  CONFIG_BRCMFMAC \
  CONFIG_BT_HCIBCM4377 \
  CONFIG_HID_APPLE \
  CONFIG_HID_MAGICMOUSE; do
  grep -E "^(${CONFIG}=|# ${CONFIG} is not set)" .config || echo "WARNING: ${CONFIG} is not present"
done

echo "=== [4/6] Building kernel image ==="
if command -v ld.lld >/dev/null 2>&1; then
  echo "Using lld as the linker (ld.lld detected)."
  export LD=ld.lld
fi

make V=1 KCFLAGS="-g0" Image.gz || { echo "Image build failed"; tail -n 200 "${LOG_FILE}"; exit 1; }

echo "=== [5/6] Building DTBs and modules ==="
make V=1 KCFLAGS="-g0" dtbs || { echo "DTB build failed"; tail -n 200 "${LOG_FILE}"; exit 1; }
make V=1 KCFLAGS="-g0" modules || { echo "Modules build failed"; tail -n 200 "${LOG_FILE}"; exit 1; }
make V=1 KCFLAGS="-g0" vmlinux || { echo "vmlinux link failed"; tail -n 400 "${LOG_FILE}"; exit 1; }

echo "=== [6/6] Packaging build output ==="
mkdir -p "${TARGET_DIR}/dist/dtbs"
mkdir -p "${TARGET_DIR}/dist/modules"

cp arch/arm64/boot/Image.gz "${TARGET_DIR}/dist/"
cp arch/arm64/boot/dts/apple/*.dtb "${TARGET_DIR}/dist/dtbs/" 2>/dev/null || true
cp vmlinux "${TARGET_DIR}/dist/" 2>/dev/null || true
cp System.map "${TARGET_DIR}/dist/" 2>/dev/null || true
cp .config "${TARGET_DIR}/dist/config" 2>/dev/null || true
cp "${LOG_FILE}" "${TARGET_DIR}/dist/" 2>/dev/null || true

KERNEL_RELEASE=$(make -s kernelrelease)
echo "Kernel release: ${KERNEL_RELEASE}"
make modules_install INSTALL_MOD_PATH="${TARGET_DIR}/dist/modules"

MODROOT="${TARGET_DIR}/dist/modules/lib/modules/${KERNEL_RELEASE}"
if [ ! -d "$MODROOT" ]; then
  echo "ERROR: module tree was not installed: $MODROOT"
  exit 1
fi

# These are generated by kbuild/modules_install and must be real files from
# this build, not placeholders.
for REQUIRED in modules.order modules.builtin modules.builtin.modinfo; do
  if [ ! -f "$MODROOT/$REQUIRED" ]; then
    echo "ERROR: missing required module metadata: $MODROOT/$REQUIRED"
    exit 1
  fi
done

KO_COUNT=$(find "$MODROOT/kernel" -type f -name '*.ko*' 2>/dev/null | wc -l)
if [ "$KO_COUNT" -eq 0 ]; then
  echo "ERROR: no kernel modules were installed under $MODROOT/kernel"
  exit 1
fi

# Generate dependency/alias metadata if available, matching a normal kernel
# module installation rather than shipping only modules.order/builtin files.
if command -v depmod >/dev/null 2>&1; then
  depmod -b "${TARGET_DIR}/dist/modules" -a "${KERNEL_RELEASE}"
fi

echo "Module tree: $MODROOT"
echo "Kernel modules installed: $KO_COUNT"
echo "Module metadata verified: modules.order modules.builtin modules.builtin.modinfo"

echo "Build output staged under ${TARGET_DIR}/dist"
echo "=========================================================================="
echo " SUCCESS: Fairydust cloud kernel build complete!                          "
echo " Build Finished: $(date)                                                  "
echo "=========================================================================="
